EQUATION("Initialization_Sector")
/*
Initializes the initial values for endogenous variables
Located at Root
Must be the first variable to be calculated
Depends on some Hypoteses:
1-All firms starts the same (implies that all average and maximum values are the same and equal to the firm value)
2-All capital goods start the same, except for the date_birth (implies that all average and maximum values are the same)
3-All demand is met initally (implies that effective orders, production and sales are the same)
4-There is no growth initally 
5-The Structure of the 4 sectors must remain (the rest below can be changed, except for input because each instance represents onE sector
*/

CYCLE(cur, "SECTORS")
{
	//SECTOR CONTROL PARAMETERS
	v[0]=VS(cur, "investment_period");
	v[1]=VS(cur, "number_object_firms");                  			//number of firms of the sector, defined by parameter
	v[2]=VS(cur, "number_object_capitals");               			//number of capital goods of each firm, defined by parameter
	v[3]=VS(cur, "avg_price_initial");                    			//initial price for all the firms under the sector
	v[4]=VS(cur, "foreign_price_initial");                			//initial foreign price for the sector
	v[5]=VS(cur, "quality_initial");					  			//initial quality for all the firms under the sector
	v[6]=VS(cur, "productivity_initial");                 			//initial productivity for all capital goods under the sector
	v[7]=VS(cur, "markup_initial");                       			//initial markup for all firms under the sector
	v[8]=VS(cur, "capital_output_ratio_initial");         			//initial capital output ratio for capital inputs under the sector
	v[9]=VS(cur, "desired_inventories_proportion");       			//desired inventories proportion for all firms under the sector	
	v[10]=VS(cur, "desired_degree_capacity_utilization"); 			//desired degree of capacity utilization for all firms under the sector
	
	v[11]=VS(cur, "input_tech_relationship_sector_3");              //how much inputs of sector 3 the current sector uses
	v[12]=VS(cur, "input_tech_relationship_sector_4");              //how much inputs of sector 4 the current sector uses
	v[13]=VS(cur, "input_tech_relationship_imports_sector_3");      //how much imported inputs of sector 3 the current sector uses
	v[14]=VS(cur, "input_tech_relationship_imports_sector_3");		//how much imported inputs of sector 4 the current sector uses
	v[15]=VS(cur, "id_sector_number");
	
	//BEGIN CALCULTATION OF ESSENTIAL INITIAL VARIABLES
	v[16]=1/v[1];                                                   //initial market share of each firm, to be written as firm's initial MS, to be written as firm's MS, desired MS, effective MS and Avg MS
	
	if (v[15]==1)													//if consumption goods sector
	{
		v[17]=v[1]*v[2]*v[8]*v[10];      							//effective orders of consumption goods sector
		v[18]=v[17]*v[11];	                                        //demand for inputs_3 generated by the sector 1
		v[19]=v[17]*v[12];											//demand for inputs_4 generated by the sector 1
	}
	if (v[15]==2)													//if capital goods sector
	{
		v[17]=v[1]*v[2]*v[8]*v[10];      							//effective orders of consumption goods sector
		v[18]=v[17]*v[11];	                                        //demand for inputs_3 generated by the sector 2
		v[19]=v[17]*v[12];											//demand for inputs_4 generated by the sector 2
	}	
	