@echo off
rem Batch generated by LSD
echo Processing 14 configuration files in up to 3 parallel processes...
if "%~1"=="" (set LSD_EXEC="C:\Lsd\Work\Artigo_Sintese_Esther_4\lsdNW.exe") else (set LSD_EXEC="%~1")
if "%~2"=="" (set LSD_CONFIG_PATH="C:\Lsd\Work\Artigo_Sintese_Esther_4\R\SA") else (set LSD_CONFIG_PATH="%~2")
set LSD_EXEC=%LSD_EXEC:"=%
set LSD_CONFIG_PATH=%LSD_CONFIG_PATH:"=%
echo LSD executable: %LSD_EXEC%
echo Configuration path: %LSD_CONFIG_PATH%
echo Use Sim.bat LSD_EXEC CONFIG_PATH to change defaults
start "LSD Process 1" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_27.lsd"    1> "%LSD_CONFIG_PATH%\Sim_27.log" 2>&1
start "LSD Process 2" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_28.lsd"    1> "%LSD_CONFIG_PATH%\Sim_28.log" 2>&1
start "LSD Process 3" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_29.lsd"    1> "%LSD_CONFIG_PATH%\Sim_29.log" 2>&1
start "LSD Process 4" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_30.lsd"    1> "%LSD_CONFIG_PATH%\Sim_30.log" 2>&1
start "LSD Process 5" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_31.lsd"    1> "%LSD_CONFIG_PATH%\Sim_31.log" 2>&1
start "LSD Process 6" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_32.lsd"    1> "%LSD_CONFIG_PATH%\Sim_32.log" 2>&1
start "LSD Process 7" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_33.lsd"    1> "%LSD_CONFIG_PATH%\Sim_33.log" 2>&1
start "LSD Process 8" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_34.lsd"    1> "%LSD_CONFIG_PATH%\Sim_34.log" 2>&1
start "LSD Process 9" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_38.lsd"    1> "%LSD_CONFIG_PATH%\Sim_38.log" 2>&1
start "LSD Process 10" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_39.lsd"    1> "%LSD_CONFIG_PATH%\Sim_39.log" 2>&1
start "LSD Process 11" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_40.lsd"    1> "%LSD_CONFIG_PATH%\Sim_40.log" 2>&1
start "LSD Process 12" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_41.lsd"    1> "%LSD_CONFIG_PATH%\Sim_41.log" 2>&1
start "LSD Process 13" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_42.lsd"    1> "%LSD_CONFIG_PATH%\Sim_42.log" 2>&1
start "LSD Process 14" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim_43.lsd"    1> "%LSD_CONFIG_PATH%\Sim_43.log" 2>&1
echo 14 log files being generated.
