@echo off
rem Batch generated by LSD
echo Processing 43 configuration files in up to 3 parallel processes...
if "%~1"=="" (set LSD_EXEC="C:\Lsd\Work\Artigo_Sintese_Esther_4\lsdNW.exe") else (set LSD_EXEC="%~1")
if "%~2"=="" (set LSD_CONFIG_PATH="C:\Lsd\Work\Artigo_Sintese_Esther_4\R\SA") else (set LSD_CONFIG_PATH="%~2")
set LSD_EXEC=%LSD_EXEC:"=%
set LSD_CONFIG_PATH=%LSD_CONFIG_PATH:"=%
echo LSD executable: %LSD_EXEC%
echo Configuration path: %LSD_CONFIG_PATH%
echo Use Sim.bat LSD_EXEC CONFIG_PATH to change defaults
start "LSD Process 1" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim" -s 1 -e 15    1> "%LSD_CONFIG_PATH%\Sim_1.log" 2>&1
start "LSD Process 2" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim" -s 16 -e 29    1> "%LSD_CONFIG_PATH%\Sim_2.log" 2>&1
start "LSD Process 3" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim" -s 30 -e 43    1> "%LSD_CONFIG_PATH%\Sim_3.log" 2>&1
echo 3 log files being generated: Sim_1.log to Sim_3.log .
